version: '3.3'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=transaction_app
      - POSTGRES_USER=jsus
      - POSTGRES_PASSWORD=randompassword
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  postgres-test:
    image: postgres:14
    environment:
      - POSTGRES_DB=transaction_app
      - POSTGRES_USER=jsus
      - POSTGRES_PASSWORD=randompassword
    ports:
      - 5431:5432
  redis:
    image: redis:7
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass randompassword
    volumes:
      - ./redis_data:/data
